# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme: fongandrew/hydeout

# Setup
title:            노머시
tagline:          '던파M'
description:      '던파 모바일 슈시아 <b>노머시길드</b> 공지페이지'
url:              https://m-dnf-nomercy.github.io
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'nenyoungam'
  url:            m-dnf-nomercy.github.io

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
disqus:
    shortname: dnf-nomercy